name: sm
channels:
  - menpo
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - attr=2.4.48=h516909a_0
  - binutils_impl_linux-64=2.40=h5293946_0
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.11.26=h06a4308_0
  - cairo=1.14.12=h8948797_3
  - elfutils=0.176=hdbcaa40_0
  - expat=2.6.4=h6a678d5_0
  - file=5.39=h5eee18b_1
  - fontconfig=2.14.1=h52c9d5c_1
  - freetype=2.12.1=h4a9f257_0
  - fribidi=1.0.10=h7b6447c_0
  - gcc=14.2.0=h96c4ede_1
  - gcc_impl_linux-64=14.2.0=h6b349bd_1
  - gettext=0.21.0=hf68c758_0
  - glib=2.63.1=h5a9c865_0
  - graphite2=1.3.14=h295c915_1 
  - gxx=14.2.0=h96c4ede_1
  - gxx_impl_linux-64=14.2.0=h2c03514_1
  - harfbuzz=1.8.8=hffaf4a1_0
  - icu=58.2=he6710b0_3
  - jpeg=9e=h5eee18b_3
  - kernel-headers_linux-64=2.6.32=he073ed8_17
  - ld_impl_linux-64=2.40=h12ee557_0
  - libarchive=3.4.2=h62408e4_0
  - libasprintf=0.22.5=he8f35ee_3
  - libcap=2.38=h516909a_0
  - libdb=6.1.26=he6710b0_0
  - libedit=3.1.20230828=h5eee18b_0
  - libffi=3.2.1=hf484d3e_1007
  - libgcc=14.2.0=h77fa898_1
  - libgcc-devel_linux-64=14.2.0=h41c2201_101
  - libgcc-ng=14.2.0=h69a702a_1
  - libgcrypt=1.11.0=h4ab18f5_1
  - libgettextpo=0.22.5=he02047a_3
  - libgomp=14.2.0=h77fa898_1
  - libgpg-error=1.50=h4f305b6_0
  - libiconv=1.16=h5eee18b_3
  - libmagic=5.39=h39e8969_1
  - libpng=1.6.39=h5eee18b_0
  - libsanitizer=14.2.0=h2a3dede_1
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-devel_linux-64=14.2.0=h41c2201_101
  - libstdcxx-ng=14.2.0=h4852527_1
  - libtiff=4.2.0=h85742a9_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.15=h7f8727e_0
  - libxml2=2.9.14=h74e7548_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - mesalib=18.3.1=h590aaf7_0
  - ncurses=6.4=h6a678d5_0
  - nspr=4.35=h6a678d5_0
  - nss=3.46.1=hab99668_0
  - openssl=1.1.1w=h7f8727e_0
  - osmesa=12.2.2.dev=0
  - pango=1.42.4=h049681c_0
  - patchelf=0.17.2=h6a678d5_0
  - pcre=8.45=h295c915_0
  - pip=24.2=py38h06a4308_0
  - pixman=0.40.0=h7f8727e_1
  - popt=1.19=h5eee18b_0
  - python=3.8.0=h0371630_2
  - python_abi=3.8=2_cp38
  - readline=7.0=h7b6447c_5
  - rpm-tools=4.15.1=py38hc3fba12_2
  - setuptools=75.1.0=py38h06a4308_0
  - spot=2.12=py38h17151c0_1
  - sqlite=3.33.0=h62c20be_0
  - sysroot_linux-64=2.12=he073ed8_17
  - tk=8.6.14=h39e8969_0
  - wheel=0.44.0=py38h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.4.9=haebb681_0
  - pip:
    - absl-py==2.1.0
    - astunparse==1.6.3
    - cachetools==5.5.0
    - certifi==2024.8.30
    - cffi==1.17.1
    - charset-normalizer==3.3.2
    - click==8.1.7
    - cloudpickle==3.0.0
    - contourpy==1.1.1
    - cycler==0.12.1
    - cython==0.29.37
    - docker-pycreds==0.4.0
    - farama-notifications==0.0.4
    - fasteners==0.19
    - filelock==3.15.4
    - flatbuffers==24.3.25
    - fonttools==4.53.1
    - fsspec==2024.6.1
    - future==1.0.0
    - gast==0.4.0
    - gitdb==4.0.11
    - gitpython==3.1.43
    - glfw==2.7.0
    - google-auth==2.34.0
    - google-auth-oauthlib==1.0.0
    - google-pasta==0.2.0
    - graphviz==0.20.3
    - grpcio==1.66.1
    - gym==0.26.2
    - gym-notices==0.0.8
    - gymnasium==0.28.1
    - h5py==3.11.0
    - highway-env==1.9.1
    - idna==3.8
    - imageio==2.35.0
    - imageio-ffmpeg==0.5.1
    - importlib-metadata==8.2.0
    - importlib-resources==6.4.0
    - jax-jumpy==1.0.0
    - jinja2==3.1.4
    - joblib==0.14.1
    - keras==2.13.1
    - kiwisolver==1.4.5
    - libclang==18.1.1
    - markdown==3.7
    - markupsafe==2.1.5
    - matplotlib==3.7.5
    - mpmath==1.3.0
    - mujoco-py==2.1.2.14
    - networkx==3.1
    - numpy==1.24.4
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu12==9.1.0.70
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-nccl-cu12==2.20.5
    - nvidia-nvjitlink-cu12==12.6.20
    - nvidia-nvtx-cu12==12.1.105
    - oauthlib==3.2.2
    - opencv-python==4.10.0.84
    - opt-einsum==3.4.0
    - packaging==24.1
    - pandas==2.0.3
    - pillow==10.4.0
    - platformdirs==4.3.6
    - protobuf==4.25.3
    - psutil==6.0.0
    - pyasn1==0.6.0
    - pyasn1-modules==0.4.0
    - pycparser==2.22
    - pygame==2.1.0
    - pyglet==1.5.0
    - pyparsing==3.1.2
    - python-dateutil==2.9.0.post0
    - pytz==2024.1
    - pyyaml==6.0.2
    - pyzmq==26.2.0
    - requests==2.32.3
    - requests-oauthlib==2.0.0
    - rsa==4.9
    - scipy==1.10.1
    - seaborn==0.13.2
    - sentry-sdk==2.18.0
    - setproctitle==1.3.3
    - six==1.16.0
    - smmap==5.0.1
    - stable-baselines3==2.0.0
    - sympy==1.13.2
    - tensorboard==2.14.0
    - tensorboard-data-server==0.7.2
    - tensorflow-estimator==2.13.0
    - tensorflow-io-gcs-filesystem==0.34.0
    - termcolor==2.4.0
    - torch==2.4.1
    - torchaudio==2.4.1
    - torchvision==0.19.1
    - tqdm==4.67.1
    - triton==3.0.0
    - typing-extensions==4.12.2
    - tzdata==2024.1
    - urllib3==2.2.2
    - wandb==0.18.6
    - werkzeug==3.0.4
    - wrapt==1.17.0
    - xmltodict==0.13.0
    - zipp==3.20.0
    - zmq==0.0.0
