name: sm
channels:
  - anaconda
  - menpo
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2024.9.24=h06a4308_0
  - cairo=1.16.0=h9f066cc_1006
  - certifi=2022.12.7=py37h06a4308_0
  - dataclasses=0.8=pyh6d0b6a4_7
  - expat=2.4.8=h27087fc_0
  - flit-core=3.6.0=pyhd3eb1b0_0
  - fontconfig=2.14.0=h8e229c2_0
  - freetype=2.10.4=h0708190_1
  - fribidi=1.0.10=h36c2ea0_0
  - gettext=0.19.8.1=hf34092f_1004
  - glew=2.1.0=h9c3ff4c_2
  - glfw3=3.2.1=0
  - graphite2=1.3.13=h58526e2_1001
  - harfbuzz=2.7.2=ha5b49bf_1
  - icu=67.1=he1b5a44_0
  - jpeg=9e=h166bdaf_1
  - libdrm-cos6-x86_64=2.4.65=4
  - libedit=3.1.20210910=h7f8727e_0
  - libffi=3.2.1=hf484d3e_1007
  - libgcc-ng=11.2.0=h1234567_1
  - libglib=2.66.3=hbe7bbb4_0
  - libglu=9.0.0=he1b5a44_1001
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.17=h166bdaf_0
  - libpng=1.6.37=h21135ba_2
  - libprotobuf=3.20.1=h4ff587b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.0.9=h648cc4a_1002
  - libtool=2.4.6=h9c3ff4c_1008
  - libuuid=2.32.1=h7f98852_1000
  - libx11-common-cos6-x86_64=1.6.4=4
  - libx11-cos6-x86_64=1.6.4=4
  - libxcb=1.13=h7f98852_1004
  - markdown=3.4.1=py37h06a4308_0
  - mesa-libgl-cos6-x86_64=11.0.7=4
  - mesa-libgl-devel-cos6-x86_64=11.0.7=4
  - mesalib=18.3.1=h590aaf7_0
  - mkl_fft=1.3.1=py37hd3c417c_0
  - mkl_random=1.2.2=py37h51133e4_0
  - ncurses=6.3=h5eee18b_3
  - numpy-base=1.21.5=py37ha15fc14_3
  - openssl=1.0.2u=h7b6447c_0
  - pango=1.42.4=h69149e4_5
  - pcre=8.45=h9c3ff4c_0
  - pip=22.1.2=py37h06a4308_0
  - pixman=0.40.0=h36c2ea0_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - python=3.7.0=h6e4f718_3
  - python_abi=3.7=2_cp37m
  - readline=7.0=h7b6447c_5
  - setuptools=63.4.1=py37h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - spot=2.10.6=py37hd23a5d3_0
  - sqlite=3.33.0=h62c20be_0
  - tk=8.6.12=h1ccaba5_0
  - typing_extensions=4.4.0=py37h06a4308_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.6.12=h36c2ea0_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxpm=3.5.13=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-libxt=1.1.5=h516909a_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.6=h5eee18b_0
  - zlib=1.2.12=h5eee18b_3
  - pip:
    - absl-py==1.2.0
    - aiohttp==3.8.4
    - aiosignal==1.3.1
    - alabaster==0.7.13
    - appdirs==1.4.4
    - astor==0.8.1
    - astunparse==1.6.3
    - async-timeout==4.0.2
    - asynctest==0.13.0
    - atari-py==0.2.9
    - attrs==23.1.0
    - babel==2.12.1
    - backcall==0.2.0
    - box2d-py==2.3.8
    - brotlipy==0.7.0
    - cachetools==5.2.0
    - cffi==1.15.1
    - charset-normalizer==2.1.0
    - click==8.1.3
    - clikit==0.6.2
    - cloudpickle==1.2.1
    - crashtest==0.3.1
    - cycler==0.11.0
    - cython==0.29.32
    - data==0.4
    - decorator==5.1.1
    - dm-reverb==0.8.0
    - dm-tree==0.1.7
    - docker-pycreds==0.4.0
    - docutils==0.18.1
    - dpcpp-cpp-rt==2022.2.0
    - exceptiongroup==1.1.1
    - farama-notifications==0.0.4
    - fasteners==0.17.3
    - flatbuffers==1.12
    - fonttools==4.37.1
    - frozenlist==1.3.3
    - funcsigs==1.0.2
    - future==0.18.2
    - gast==0.5.3
    - gitdb==4.0.10
    - gitpython==3.1.31
    - glfw==2.5.4
    - google-auth==2.10.0
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - graphviz==0.20.1
    - grpcio==1.47.0
    - gym==0.15.7
    - gym-notices==0.0.8
    - gymnasium==0.28.1
    - h5py==3.7.0
    - httpstan==4.6.1
    - idna==3.3
    - imagehash==4.3.1
    - imageio==2.21.1
    - imageio-ffmpeg==0.5.1
    - imagesize==1.4.1
    - importlib-metadata==4.12.0
    - iniconfig==2.0.0
    - intel-cmplr-lib-rt==2022.2.0
    - intel-cmplr-lic-rt==2022.2.0
    - intel-opencl-rt==2022.2.0
    - intel-openmp==2022.2.0
    - ipdb==0.13.13
    - ipython==7.34.0
    - jax-jumpy==1.0.0
    - jedi==0.18.2
    - jinja2==3.1.2
    - joblib==0.14.1
    - keras==2.9.0
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - kiwisolver==1.4.4
    - latex==0.7.0
    - libclang==14.0.6
    - lockfile==0.12.2
    - markupsafe==2.1.1
    - marshmallow==3.19.0
    - matplotlib==3.1.1
    - matplotlib-inline==0.1.6
    - mkl==2022.2.0
    - mkl-fft==1.3.1
    - mkl-service==2.4.0
    - mpmath==1.2.1
    - mujoco-py==2.1.2.14
    - multidict==6.0.4
    - numpy==1.21.6
    - numpydoc==1.5.0
    - oauthlib==3.2.0
    - opencv-python==4.6.0.66
    - packaging==21.3
    - pandas==1.1.5
    - parso==0.8.3
    - pastel==0.2.1
    - patchelf==0.17.2.1
    - pathtools==0.1.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==9.2.0
    - pluggy==1.0.0
    - portpicker==1.5.2
    - prompt-toolkit==3.0.38
    - protobuf==3.19.4
    - psutil==5.9.1
    - ptyprocess==0.7.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.21
    - pygame==2.1.0
    - pyglet==1.5.0
    - pygments==2.15.1
    - pylev==1.4.0
    - pyopengl==3.1.6
    - pyparsing==3.0.9
    - pysimdjson==3.2.0
    - pystan==3.3.0
    - pytest==7.3.1
    - pytest-instafail==0.3.0
    - python-dateutil==2.8.2
    - pytz==2022.2.1
    - pywavelets==1.3.0
    - pyyaml==6.0
    - requests==2.28.1
    - requests-oauthlib==1.3.1
    - rlds==0.1.5
    - rsa==4.9
    - scipy==1.7.3
    - seaborn==0.8.1
    - sentry-sdk==1.21.1
    - setproctitle==1.3.2
    - shutilwhich==1.1.0
    - smmap==5.0.0
    - snowballstemmer==2.2.0
    - sphinx==5.3.0
    - sphinx-rtd-theme==1.2.0
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==2.0.0
    - sphinxcontrib-jquery==4.1
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.5
    - stable-baselines3==2.0.0
    - sympy==1.10.1
    - tbb==2021.7.0
    - tempdir==0.7.1
    - tensorboard==1.14.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow-estimator==1.14.0
    - tensorflow-gpu==1.14.0
    - tensorflow-io-gcs-filesystem==0.26.0
    - termcolor==1.1.0
    - tomli==2.0.1
    - torch==1.12.1
    - torchaudio==0.12.1
    - torchvision==0.13.1
    - tqdm==4.64.0
    - traitlets==5.9.0
    - typing-extensions==4.3.0
    - urllib3==1.26.11
    - wandb==0.15.1
    - wcwidth==0.2.6
    - webargs==8.1.0
    - werkzeug==2.2.2
    - wrapt==1.14.1
    - xmltodict==0.13.0
    - yarl==1.9.2
    - zipp==3.8.1
